apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-cluster-secret-store
spec:
  provider:
    gcpsm:
      projectID: "${gcp_project_id}"
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: ${gcp_sa_sm_secret_name}
            key: credentials.json
            namespace: "${external_secrets_helm_release_namespace}"
