apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: cloudflare-kubernetes-gateway
    app.kubernetes.io/managed-by: kustomize
  name: cloudflare-controller-manager
  namespace: ${gateway_api_namespace}
