namespaceOverride: "${metallb_helm_release_namespace}"

controller:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

speaker:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  livenessProbe:
    timeoutSeconds: 5
  readinessProbe:
    timeoutSeconds: 5
  startupProbe:
    failureThreshold: 60
  frr:
    enabled: true
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  reloader:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
  frrMetrics:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

frrk8s:
  enabled: false

prometheus:
  serviceMonitor:
    enabled: false
