namespaceOverride: ${infra_storage_namespace}
preUpgradeChecker:
  jobEnabled: true
  upgradeVersionCheck: true
metrics:
  serviceMonitor:
    enabled: false
longhornManager:
  nodeSelector: { }
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  log:
    format: json
longhornDriver:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  log:
    format: json
longhornUI:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi
  log:
    format: json
persistence:
  shareManagerTolerations: true
defaultSettings:
  deletingConfirmationFlag: true
