[proxmox_nodes]
proxmox-node1 ansible_host=198.27.70.67
proxmox-node3 ansible_host=135.125.223.213
proxmox-node4 ansible_host=37.187.157.64
proxmox-node5 ansible_host=37.187.159.125

[proxmox_master]
proxmox-node1

[proxmox_workers]
proxmox-node3
proxmox-node4
proxmox-node5

[proxmox_nodes:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
