namespaceOverride: "${argo_cd_helm_release_namespace}"
global:
  domain: "${argocd_ingress_domain}"

configs:
  params:
    server.insecure: true
  cm:
    # language=yaml
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $argocd-github-sso-secret:clientID
            clientSecret: $argocd-github-sso-secret:clientSecret
            orgs:
              - name: ${github_org}
  rbac:
    policy.default: role:readonly
    # language=csv
    policy.csv: |
      g, ${github_org}:${github_sso_admin_team}, role:admin

server:
  replicas: 3
  service:
    type: ClusterIP
  ingress:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

controller:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

repoServer:
  replicas: 2
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

applicationSet:
  replicas: 2
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

redis:
  enabled: false

redis-ha:
  enabled: true
  replicas: 3
  redis:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
  sentinel:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi

ha:
  enabled: true

dex:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
