---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: github-org-discovery
  namespace: ${argo_cd_helm_release_namespace}
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - scmProvider:
              cloneProtocol: https
              github:
                organization: ${argo_cd_github_org}
                appSecretName: github-app-repo-creds
              filters:
                - labelMatch: 'argocd-infra'
          - git:
              repoURL: 'https://github.com/KarafrOrg/{{ .repository }}'
              revision: 'HEAD'
              directories:
                - path: '*'
  template:
    metadata:
      name: '{{ .repository | lower | replace "_" "-" }}-{{ .path.basename }}'
      namespace: ${argo_cd_helm_release_namespace}
    spec:
      project: default
      source:
        repoURL: '{{ .url }}'
        targetRevision: '{{ .branch }}'
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .repository | lower | replace "_" "-" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
