---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-repo-creds
  namespace: ${argo_cd_helm_release_namespace}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: github-app-repo-creds
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: "https://github.com/${github_org}"
        githubAppID: "{{ .githubAppID }}"
        githubAppInstallationID: "{{ .githubAppInstallationID }}"
        githubAppPrivateKey: "{{ .githubAppPrivateKey }}"
  data:
    - secretKey: githubAppID
      remoteRef:
        key: ${github_app_id_gcp_secret_id}
    - secretKey: githubAppInstallationID
      remoteRef:
        key: ${github_app_installation_id_gcp_secret_id}
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: ${github_app_private_key_gcp_secret_id}
