apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-sso
  namespace: ${argo_cd_helm_release_namespace}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-github-sso-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: clientID
      remoteRef:
        key: ${github_sso_client_id_gcp_secret_id}
    - secretKey: clientSecret
      remoteRef:
        key: ${github_sso_client_secret_gcp_secret_id}
