apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: monitoring-elasticsearch
  namespace: ${alloy_helm_release_namespace}
spec:
  auth:
    roles:
      - secretName: monitoring-elasticsearch-otel-role
